get http://localhost:3003/api/blogs

###
get http://localhost:3003/api/blogs/5eaaada854764f3e42705d61

###
post http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Core building blocks of React",
  "author": "Tringa Krasniqi",
  "url": "https://dev.to/tringakrasniqi/core-building-blocks-of-react-3dk7",
  "likes": "10"
}
